// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"context"
	"github.com/google/wire"
	"github.com/yusufwib/blockchain-medical-record/config"
	"github.com/yusufwib/blockchain-medical-record/handler"
	"github.com/yusufwib/blockchain-medical-record/repository"
	"github.com/yusufwib/blockchain-medical-record/service"
	"github.com/yusufwib/blockchain-medical-record/utils/logger"
	"github.com/yusufwib/blockchain-medical-record/utils/mvalidator"
	"gorm.io/gorm"
)

// Injectors from dependency.go:

func NewDependency(context2 context.Context, logger mlog.Logger, validator mvalidator.Validator, config2 *config.ConfigGroup, database *gorm.DB) *Dependency {
	userRepository := repository.NewUserRepository(database, config2)
	userService := service.NewUserService(userRepository)
	iUserHandler := handler.NewUserHandler(context2, logger, validator, userService)
	healthRepository := repository.NewHealthRepository(database, config2)
	healthService := service.NewHealthService(healthRepository)
	iHealthHandler := handler.NewHealthHandler(context2, logger, validator, healthService)
	dependency := &Dependency{
		UserHandler:   iUserHandler,
		HealthHandler: iHealthHandler,
	}
	return dependency
}

// dependency.go:

type Dependency struct {
	UserHandler   handler.IUserHandler
	HealthHandler handler.IHealthHandler
}

var setUserHandler = wire.NewSet(repository.NewUserRepository, service.NewUserService, handler.NewUserHandler)

var setHealthHandler = wire.NewSet(repository.NewHealthRepository, service.NewHealthService, handler.NewHealthHandler)
